name: Test Bash Script

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/gh-actions-lxd@v1
        with:
          channel: latest/stable
      - name: Launch instance
        run: |
          lxc launch ubuntu:20.04 test
