name: Test Bash Script

on:
  push:
    branches: [ master ]

jobs:
  Build:
    name: Test Build Bash Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: antyung88/gh-actions-lxd@v2.1
        with:
          channel: latest/stable
      - name: Launch instance
        run: |
          sudo chmod +x ./zabbix.sh
          sudo ././zabbix.sh
